
import os
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

print(f"URL: {SUPABASE_URL}")
print(f"KEY: {SUPABASE_KEY[:10]}...") 

try:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    
    # PASTE YOUR TOKEN HERE TO TEST
    TEST_TOKEN = "eyJhbGciOiJFUzI1NiIsImtpZCI6ImE5MGIwZWJiLTYxZTktNDBlNy1iMzRmLTI1NTgwNTdjYjAwMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL29nbnVzamdveXZoaWh5cGJ0Z3ZsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxZjlhYWU1Ni05YjRjLTQ0MGItOWU5NS0yNjk2NWM4NmVkNzciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzcxNTI0NTQzLCJpYXQiOjE3NzE1MjA5NDMsImVtYWlsIjoiYXN3aW5iaW9AZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnb29nbGUiLCJwcm92aWRlcnMiOlsiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKWnpBSWdXZUZJRWc4SVVGMHJwdDRPbGtEdjE3cTlHeFZDVmNYeFdZLUVWSXFuSWFLOTVnPXM5Ni1jIiwiZW1haWwiOiJhc3dpbmJpb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiQXN3aW4gTWFub2hhciIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IkFzd2luIE1hbm9oYXIiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKWnpBSWdXZUZJRWc4SVVGMHJwdDRPbGtEdjE3cTlHeFZDVmNYeFdZLUVWSXFuSWFLOTVnPXM5Ni1jIiwicHJvdmlkZXJfaWQiOiIxMDI5MjcyMjA5MTMyNzIzNDI5MjIiLCJzdWIiOiIxMDI5MjcyMjA5MTMyNzIzNDI5MjIifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvYXV0aCIsInRpbWVzdGFtcCI6MTc3MTUyMDk0M31dLCJzZXNzaW9uX2lkIjoiNDRmMjg3YjMtYWYyYS00MGE0LTllZDctYjY1ZmZmNjhhMjdjIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.RiW4c_seVeemJcCoQ7TFC1MRuP_uRJ4eEf4NxaQ8DRrrz_CAi7Sv_z1xoWl0sjbT-vPPmOHc-urXQvUKrtH-Ow"

    print("\nAttempting to get user...")
    user = supabase.auth.get_user(TEST_TOKEN)
    print("SUCCESS!")
    print(f"User ID: {user.user.id}")

except Exception as e:
    print(f"\nFAILED: {e}")
